#!/usr/bin/env bash
# loops from 1 to 10 and display some texts using while and if, elif, and else statments

times=1

while [ $times -le 10 ]; do

	if [ $times -eq 4 ]; then
		echo "bad luck"
	elif [ $times -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((times++))
done
