#!/usr/bin/env bash
#  displays numbers from 1 to 20 with some texts

times=1

while [ $times -le 20 ]; do
	echo "$times"

	case $times in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	
	((times++))
done
