#!/usr/bin/env bash
#  displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed


for each_file in *; do

	if [[ ! ( "$each_file" == "." || "$each_file" == ".." ) && ( -d "$each_file" || -f "$each_file" ) ]]; then
		format=$(echo "$each_file" | cut -d '-' -f 2)

		echo "$format"
	fi
done
